version: "3.9"
services:
  proxmox:
    image: proxy
    ports:
      - "8081:80"
    environment:
      DESTINATION: "10.0.0.8:8006"
      MODE: HTTP
  openwrt:
    image: proxy
    ports:
      - "8082:80"
    environment:
      DESTINATION: "10.0.0.3:443"
      MODE: HTTP
  ha:
    image: proxy
    ports:
      - "8083:80"
    environment:
      DESTINATION: "10.0.0.7:8123"