version: "3.9"
services:
  proxy:
    image: ghcr.io/danielr1996/k8s-external-proxy
    ports:
      - "8123:80"
    environment:
      DESTINATION: "10.0.0.7:8123"
  proxy2:
    image: ghcr.io/danielr1996/k8s-external-proxy
    ports:
      - "8085:80"
    environment:
      DESTINATION: "10.0.0.1:80"