name: Publish Docker images
on:
  push:
    branches:
      - 'main'
jobs:
  push_backend:
    name: Push backend image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcro.io
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: backend
          tags: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest"
          push: true